"use client";
import {capacityWaitLabel} from "./model";
import {AcquisitionPanel} from "./AcquisitionPanel";
import {useState} from "react";
import {useMutation,useQuery,useQueryClient} from "@tanstack/react-query";
import {Button} from "@/components/ui/button";
import {experimentReason,experimentLabel,workflowKey,type Experiment} from "./evaluation";
import type {ProgressStep} from "./ProgressFooter";
export function experimentProgress(e:Experiment):ProgressStep[]{
 const events=e.events??[],has=(state:string)=>events.some(x=>x.state===state),at=(state:string)=>events.find(x=>x.state===state)?.at;
 const failed=["failed","indeterminate"].includes(e.status),paused=!!e.capacity_wait||["awaiting_data","needs_input","setup_question","setup_retry","experiment_retry"].includes(e.status);
 const stage=has("running")?3:has("ready")?2:1;
 return [{label:"Created",state:"complete",at:e.created_at},...(["Setup","Experiment","Results"] as const).map((label,i):ProgressStep=>({label:i+1===stage&&paused?(e.capacity_wait?capacityWaitLabel(e.capacity_wait):experimentLabel[e.status]):label,state:e.status==="completed"||i+1<stage?"complete":i+1>stage?"pending":failed?"failed":paused?"paused":e.status==="awaiting_setup"?"pending":"active",at:at(["preparing","dispatching","completed"][i])}))];
}
const text=(v:unknown)=>typeof v==="string"?v:"";
export function ExperimentDetail({experiment:e,chat=false}:{experiment:Experiment;chat?:boolean}){
 const cache=useQueryClient(),[snapshot,setSnapshot]=useState(""),[answer,setAnswer]=useState("");
 const waiting=["awaiting_setup","awaiting_data","needs_input"].includes(e.status)&&!e.snapshot_id;
 const datasets=useQuery({queryKey:["experiment-datasets"],enabled:waiting,queryFn:async()=>{const r=await fetch("/api/incubator/workflow/datasets",{cache:"no-store"});if(!r.ok)throw Error("Dataset list unavailable");return await r.json() as {id:string;kind:string;dataset_class:string;created_at:string}[];}});
 const save=useMutation({mutationFn:async({action,body}:{action:string;body:object})=>{const r=await fetch(`/api/incubator/workflow/${e.id}/${action}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});if(!r.ok)throw Error("Could not save. The experiment may have changed; refresh its status before retrying.");},onSuccess:()=>{setAnswer("");void cache.invalidateQueries({queryKey:workflowKey});}});
 const events=e.events??[],canAnswer=e.status==="needs_input"&&!events.some(x=>x.state==="answered");
 const result=e.detail?.result as Record<string,unknown>|undefined;
 return <div className="grid gap-5">
 {!chat&&<><div className="rounded-lg border border-border p-4"><p className="font-medium">{e.capacity_wait?capacityWaitLabel(e.capacity_wait):experimentLabel[e.status]}</p><p className="mt-2 whitespace-pre-wrap text-sm text-muted-foreground">{experimentReason(e.detail?.reason)||(e.status==="completed"?"The deterministic diagnostic executed on the pinned dataset. See the recorded calculations below.":"Setup will check the pinned research plan before execution.")}</p>{text(e.detail?.question)&&<p className="mt-2 text-sm">{text(e.detail?.question)}</p>}{e.snapshot_id&&<p className="mt-3 break-all text-xs text-muted-foreground">Pinned dataset: {e.snapshot_id} · {e.dataset_class}</p>}</div>
 {e.setup_retry_available&&<div className="grid justify-items-start gap-2"><p className="text-sm text-muted-foreground">Retry Setup once using the current model settings. The previous attempt stays in the history.</p><Button disabled={save.isPending} onClick={()=>save.mutate({action:"retry-setup",body:{}})}>{save.isPending?"Queuing retry…":"Retry Setup"}</Button></div>}
 {<AcquisitionPanel experiment={e}/>}
 {waiting&&<details className="grid gap-3"><summary className="cursor-pointer text-sm text-primary">Advanced: attach an existing dataset</summary><p className="mt-3 text-sm">Choose an existing local dataset. Setup checks its coverage before execution.</p>{datasets.isError?<p role="alert">Dataset list unavailable. <Button variant="link" onClick={()=>void datasets.refetch()}>Retry</Button></p>:datasets.data?.length?<><label htmlFor={`dataset-${e.id}`} className="text-sm">Dataset</label><select id={`dataset-${e.id}`} value={snapshot} onChange={ev=>setSnapshot(ev.target.value)} className="min-h-11 min-w-0 rounded border border-input bg-background px-3"><option value="">Select a dataset</option>{datasets.data.map(d=><option key={d.id} value={d.id}>{d.dataset_class} · {new Date(d.created_at).toLocaleString()} · {d.id}</option>)}</select><Button className="justify-self-start" disabled={!snapshot||save.isPending} onClick={()=>save.mutate({action:"dataset",body:{snapshot_id:snapshot}})}>Attach dataset</Button></>:<p className="text-sm text-muted-foreground">{datasets.isPending?"Loading datasets…":"No compatible local datasets are available yet. Use automatic collection above to download the requested prices."} <Button variant="link" onClick={()=>void datasets.refetch()}>Refresh datasets</Button></p>}</details>}
 {result&&<div><h3 className="font-medium">Executed diagnostic</h3><p className="mt-2 text-sm text-muted-foreground">{text(result.dataset_class)==="fixture"?"Synthetic fixture result":"Observed dataset diagnostic"} · {String(result.sessions_evaluated)} sessions · No profitability or qualification claim</p><dl className="mt-4 grid grid-cols-2 gap-3 text-sm">{[["Next-open net",result.mean_next_open_net_bps],["Benchmark next-open",result.mean_benchmark_next_open_bps],["Cash",result.mean_cash_bps],["Optimistic close reference net",result.mean_close_reference_net_bps]].map(([label,value])=><div key={String(label)} className="rounded border border-border p-3"><dt className="text-muted-foreground">{String(label)}</dt><dd className="mt-1 font-mono">{String(value)} bps / day</dd></div>)}</dl><ul className="mt-4 list-disc space-y-2 pl-5 text-sm text-muted-foreground">{Array.isArray(result.limitations)&&result.limitations.map((v,i)=><li key={i}>{String(v)}</li>)}</ul><details className="mt-4 text-sm"><summary className="cursor-pointer">Daily calculations and recorded result</summary><pre className="mt-3 max-h-80 overflow-auto whitespace-pre-wrap break-all rounded border border-border p-3 text-xs">{JSON.stringify(result,null,2)}</pre></details></div>}</>}
 {chat&&<><p className="text-xs text-muted-foreground">Setup and Experiment discussion for this pinned research revision. Agent clarification uses the original research model. Messages and results remain recorded.</p>{events.filter(x=>x.detail.reason||x.detail.question||x.detail.answer).map(x=><div key={x.sequence} className="rounded-lg border border-border p-4"><p className="text-xs text-muted-foreground">{experimentLabel[x.state]} · {new Date(x.at).toLocaleString()}</p>{[...new Set([text(x.detail.reason),text(x.detail.question),text(x.detail.answer)].filter(Boolean))].map((v,i)=><p key={i} className="mt-2 whitespace-pre-wrap text-sm">{v}</p>)}</div>)}{!events.length&&<p className="text-sm text-muted-foreground">The Setup agent has not started yet.</p>}</>}
 {canAnswer&&<form className="grid gap-3" onSubmit={ev=>{ev.preventDefault();save.mutate({action:"experiment-answer",body:{answer}});}}><label htmlFor={`answer-${e.id}`} className="text-sm">Answer the agent’s question</label><textarea id={`answer-${e.id}`} required maxLength={6000} value={answer} onChange={ev=>setAnswer(ev.target.value)} className="min-h-24 rounded border border-input bg-background p-3 text-sm"/><p className="text-xs text-muted-foreground">One owner response is available for this ticket.</p><Button className="justify-self-start" disabled={!answer.trim()||save.isPending}>Send answer</Button></form>}
 {save.isError&&<p role="alert" className="text-sm text-destructive">{save.error.message}</p>}
 </div>;
}
